### ISSUE TITLE
Git remotes get added to config file multiple times

### ISSUE THREAD

**Issue by gingermusketeer** [boxen/puppet-inifile#2]
Trying to use the ini_setting type in boxen to set some remotes for repositories

The following creates a new section every time it is run

``` pp
  ini_setting { "setting remote fetch config for some/repo":
    ensure  => present,
    path    => 'some/path,
    section => '[remote "production"],
    setting => 'fetch',
    value   => '+refs/heads/*:refs/remotes/origin/*',
  }
```

Is it something to do with the section detection?

**Comment by bschlief** [comment]
+1.  Single character git aliases show the same behavior of creating new entries and running on ever boxen run.
